Update update.yml

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -2,7 +2,7 @@ name: Update Subscription
 
 on:
   schedule:
-    - cron: "*/1440 * * * *"   # هر 10 دقیقه یکبار (بر اساس UTC)
+    - cron: "*/10 * * * *"   # هر 10 دقیقه یکبار (بر اساس UTC)
   workflow_dispatch:          # امکان اجرای دستی
 
 permissions:
@@ -21,7 +21,10 @@ jobs:
         run: |
           set -e
           # دریافت خروجی از Worker
-          curl -fsSL "http://set.ahw85.ir:8080/sub/vless_raw.txt" -o SE-con.new
+          if ! curl -fsSL "http://set.ahw85.ir:8080/sub/vless_raw.txt" -o SE-con.new; then
+            echo "Download failed, skipping this run."
+            exit 0
+          fi
           
           # اضافه کردن کانفیگ‌های دستی
           echo "" >> SE-con.new
